# Generated by Django 2.2.12 on 2020-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeslist',
            name='author',
        ),
        migrations.AlterField(
            model_name='storeslist',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeslist',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storeslist',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storeslist',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
