# Generated by Django 2.2.12 on 2020-05-04 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinpic', '0002_auto_20200503_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeslist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeslist',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storeslist',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
